[preface]
:sectnums!:

= はじめに

== この本について

この本では、Go言語の標準パッケージである `go/*` について、実例を交えながら紹介します。以下のパッケージが対象です。

* go/ast
* go/build
* go/constant
* go/doc
* go/format
* go/importer
* go/parser
* go/printer
* go/scanner
* go/token
* go/types

この本は、ドキュメントとソースコードの中間となることを目指します。ドキュメントだけからはただちに知ることのできない、API同士の関連や、全体としての使い方に焦点を当てています。

この本が、Goにおけるコード解析や生成のためのツールを書く際の助けになると幸いです。

== なぜ「GoのためのGo」なのか

Go言語はシンプルさを念頭にデザインされた言語です。仕様は単純明瞭さのために小さく収められていますが、そのため表現力に欠けているとか、コードが冗長になるという印象を持つ人も多いでしょう。有名なところでは、ジェネリクスや例外といった機能が（今のところ）存在しないことが問題にされることが多いようです。

一般に、ソフトウェアエンジニアリングというものは書かれる言語だけに依るものではありません。視点を拡げ、Goを取りまくツール群を含めて見てみると、`go fmt` や link:https://godoc.org/golang.org/x/tools/cmd/goimports[`goimports`] といったツールが広く使われていること、また link:https://blog.golang.org/generate[`go generate`] コマンドの存在などを見ても、人間のプログラミングを機械によってさまざまな面から補助しようという態度がGoという言語にはあります。

`go/*` 標準パッケージは、Goのプログラムを対象とし、解析や操作を行うためのAPIを提供します。これらのAPIを利用し、一種のメタプログラミングを行うことで、Goプログラミングの力をより引き出せるようになるはずです。

== 対象バージョン

この本の内容は、Goバージョン1.7.4に基いています。

:sectnums:
