= 型解析

ここまで見てきたようなGoの抽象構文木を扱うAPIを知っていれば、Goプログラムを対象にしてできることの7割ほどは実現できたも同然です。しかし、

* ソースコード中に登場する名前が定義された位置や、
* ある型がインタフェースを実装しているか

など、プログラムの構造を越えたより高度な情報が必要になった場合は、**型解析**に手を出す必要があります。

この章では、Goパッケージの型チェックと型にまつわるデータ構造を提供する `go/types` パッケージのAPIを見ていきます。

- 名前解決
- 定数畳み込み
- 型推論

== 型チェックを行う

`types` パッケージによる型チェックは、`types.Config` 構造体の `Check` メソッドを呼ぶところから始まります。

godoc::go/types.Config.Check[]

`files []ast.File` には、ひとつのパッケージを構成する構文解析されたファイル群を指定します。<<ファイルの構文解析>> で `files` の要素を生成した際に使用した `fset` も引数として渡します。

最後の引数である `info *types.Info` は、パッケージ内の型にまつわる詳細な情報を格納する先として指定します。単純に型チェックを行いたいだけの場合は `nil` でも構いません。

goexample::typechecksimple[]

goexample::typechecksimple[output]

パッケージのトップレベルに定義された `s` という変数の型が `string` であるという情報が得られました。

このように、型チェックおよび型情報の取得は `Config` 構造体をエントリポイントとしてパッケージごとに行います。結果は <<types.Package>> 構造体と、ここでは登場しませんでしたが <<types.Info>> 構造体に格納されます。

== パッケージのインポート

先ほどの例では `Config.Importer` を設定していました。これは `types.Importer` という型を持つフィールドです。

godoc::go/types.Importer[]

`types.Importer` は、パッケージのパスを解決し、そのパッケージに関する型レベルの情報を返すインタフェースです。具体的には、コンパイルされたパッケージオブジェクトを `GOPATH` から探し出し、解析するのが仕事です。

この具体的な実装を提供するのが `go/importer` パッケージです。`importer.Default()` は実行中のバイナリのコンパイラ（`runtime.Compiler`）に対応するインポートの実装を返します。

godoc::go/importer.Default[]

以下はパッケージを読み込み、そのパッケージが公開している名前および依存しているパッケージの情報を印字する例です。

goexample::importer[]

goexample::importer[output]

プログラムの型チェックにはインポートしているパッケージがどんな名前と型を提供するのか知る必要があるため、`Config` 構造体の `Importer` フィールドという形でその実装を指定します。

== types.Config

`types.Config` 構造体が、`go/types` パッケージのエントリポイントとなります。

godoc::go/types.Config[]

各フィールドを調整することで、`Check()` による型チェックを行う際の挙動をカスタマイズできます。

特に、`Error func(err error)` は型チェックの際に生じたエラーを全て受け取るコールバックとして便利です。

== 型チェックのエラー

型チェック時のエラーは `types.Error` 構造体によって表現されます。

godoc::go/types.Error[]

エラーの起きた位置情報に加え、`Soft` フィールドを持っています。このフィールドは、当該のエラーが「ソフト」であるかどうかを示します。ソフトなエラーは、型チェックそのものには影響を与えません。具体的には、以下のエラーです。

* `import` されたパッケージが使用されていない
* 定義された変数が使用されていない
* ラベルが利用されていない・重複している
* `:=` の左辺に新しい変数が登場していない
* `init` 関数の本体が存在しない
// 関数の本体については https://golang.org/ref/spec#Function_declarations
* C形式の `for` 文の後処理部で変数を定義しようとしている
// たぶん構文解析時点では通ってしまう。parseSimpleStmt

// TODO: 型チェックだけでなくこういう言語的なチェックも行われること初めの方で言及

////
% pt --nogroup -w softErrorf src/go/types
src/go/types/labels.go:38:			check.softErrorf(lbl.pos, "label %s declared but not used", lbl.name)
src/go/types/labels.go:136:					check.softErrorf(lbl.pos, "label %s already declared", name)
src/go/types/labels.go:151:							check.softErrorf(
src/go/types/errors.go:89:func (check *Checker) softErrorf(pos token.Pos, format string, args ...interface{}) {
src/go/types/resolver.go:356:							check.softErrorf(obj.pos, "missing function body")
src/go/types/resolver.go:456:						check.softErrorf(obj.pos, "%q imported but not used", path)
src/go/types/resolver.go:458:						check.softErrorf(obj.pos, "%q imported but not used as %s", path, obj.name)
src/go/types/resolver.go:468:			check.softErrorf(pos, "%q imported but not used", pkg.path)
src/go/types/assignments.go:329:		check.softErrorf(pos, "no new variables on left side of :=")
src/go/types/stmt.go:62:			check.softErrorf(v.pos, "%s declared but not used", v.name)
src/go/types/stmt.go:565:				check.softErrorf(lhs.Pos(), "no new variable on left side of :=")
src/go/types/stmt.go:644:				check.softErrorf(lhs.Pos(), "%s declared but not used", lhs.Name)
src/go/types/stmt.go:710:			check.softErrorf(s.Pos(), "cannot declare in post statement")
////

以下で、ソフトなエラーとそうでない重篤なエラーの例を確認できます。

goexample::typecheckerrors[]

goexample::typecheckerrors[output]

== パッケージの型情報

=== types.Package

=== types.Info

== スコープ

== 型とオブジェクト

=== types.Type

=== types.Object

[appendix]
== types.Typeの階層

----
include::listings/types-type-hierarchy.txt[]
----

[appendix]
== types.Objectの階層

----
include::listings/types-object-hierarchy.txt[]
----
