= ソースコードを読む

ここではGoプログラマに広く使われているツール類のソースコードを読むことで、実戦でどのようにAPIが利用されているかを見ていきます。

== go doc

パッケージのAPIのドキュメントを閲覧する機能を提供するサブコマンドです。
`go doc go/ast Node` のようにパッケージやシンボルを指定すると、そのドキュメントを表示します。

パッケージ名は完全なパスでなくてもよく、その場合はGOPATH以下からマッチするものを探してきます。

ソースは `src/cmd/doc/` 以下にあります。

// TODO: godoc との関係
// TODO: 概要

=== 引数の解決（`parseArgs`）

最初に、引数で指定された要件にしたがってドキュメントの元となるソースコードを取得します。

`go doc` への引数の与え方はさまざまで、パッケージを指定する方法には次の3パターンがあります：

a. カレントディレクトリのソースコードを対象にする（例：`go doc`）。
b. 完全なパスで指定されたパッケージを対象にする（例：`go doc encoding/json`）。
c. 指定されたパスの一部からパッケージを探しだす（例：`go doc json`）。

これに加えて、パッケージ内のシンボルおよびそのメソッドも指定されることがあります。

カレントディレクトリを対象にする場合およびパッケージが指定されている場合（aおよびb）は、`go/build` のAPI `build.Import` を使って簡単にソースコードの所在を示す `build.Package` が得られます。

そうでない場合（c）、パスの一部が一致するパッケージを発見する必要があります。ここでも `go/build` のAPIを利用し、`build.Default.GOROOT` と `build.Default.GOPATH` 以下のディレクトリを探索します。`go doc` コマンドが実行された時点でこの探索のためのgoroutineが起動していて、すばやく結果を返せるようになっています。

=== ソースコードの解析（`parsePackage`）

ドキュメント情報を得るためには、ソースコードを解析する必要があります。パッケージの情報が手元にあるので `parser.ParseDir` でディレクトリ内のファイルを一度に解析できますが、その際第3引数の `filter` を指定して `GoFiles` や `CgoFiles` に含まれないものを除去します。こうすることで、実行環境（`GOOS` や `GOARCH`）に合わせたソースコードのみを解析対象としています。

[source,go]
----
pkgs, err := parser.ParseDir(fs, pkg.Dir, include, parser.ParseComments)
----

その後 `doc.New` して得られた `doc.Package` から `Package` 構造体を生成します。

=== ドキュメントの表示（`Pacakge.packageDoc` など）

`Package` 構造体の以下のメソッドがモードに応じて選ばれ、ユーザに表示される内容を生成します。

* `packageDoc` ... パッケージのドキュメントを表示
* `symbolDoc`  ... シンボル（型、関数、メソッドなど）のドキュメントを表示
* `methodDoc`  ... ある型のメソッドのドキュメントを表示

ドキュメントを表示するなかで対象のソースコードにおける定義が必要になった場合（`go doc go/ast File` など）、`format.Node` で生成されます。`ast.FuncDecl` を表示する際は `Body` フィールドに `nil` を代入することで、宣言のみが表示されるようにしています。

== gofmt

Goにおいて特徴的なコマンドで、ソースコードを標準的なスタイルにフォーマットします。ほとんどのGoプログラマが利用しているコマンドです（たぶん）。

=== gofmtの主なインタフェース

何もオプションを指定しない場合、gofmtは引数のファイルまたは標準入力をフォーマットして、標準出力に印字します。

よく利用されるのは `-w` で、これが指定された場合結果は引数のファイルを上書きするのに使われます。また `-d` では、入力の内容と結果の `diff` が表示されます。

ソースコードは `src/cmd/gofmt` 以下にあります。

=== ソースコードの印字

WARNING: WIP

=== `-s`: ソースをシンプルにする

通常gofmtが行うのはソースコードの整形のみで、抽象構文木の構造が変わるような変更を行いませんが、`-s`や`-r`を指定することでより積極的なフォーマットが可能です。

このオプションが指定された場合、ソースコードの印字の前に `simplify(f *ast.File)` が呼び出されます。

最初に `const ()` のような空の宣言が取り除かれます。これは `ast.File.Decls` を書き換えることで実現できます（link:https://github.com/golang/go/blob/go1.6/src/cmd/gofmt/simplify.go#L137-146[`removeEmptyDeclGroups`]）。

// TODO: gosource:src/cmd/gofmt/simplify.go#L137-146[go1.6] みたいにしたい

それから、構文木を辿って単純化が行われます。適用されるのは以下のルールになります。

// TODO 例
* 複合リテラルの単純化
* スライスの単純化（`s[a:len(s)]` → `s[a:]`）
* for/range文の単純化（`for _ = range` → `for range`）

スライスとfor/range文の単純化はどちらかというと単純な作業で、type assertionを利用しながら構文木を探索し、求める構造に合致するノードを発見します。合致した場合、消し去りたい部分を表すフィールドに `nil` を代入することで結果のソースコードから削除しています。

TODO: match()

=== `-r`: ソースを書き換える

== stringer

== guru

== goimports

== gddo
