= ソースコードを読む

ここではGoプログラマに広く使われているツール類のソースコードを読むことで、実戦でどのようにAPIが利用されているかを見ていきます。

== go doc

パッケージのAPIのドキュメントを閲覧する機能を提供するサブコマンドです。
`go doc go/ast Node` のようにパッケージやシンボルを指定すると、そのドキュメントを表示します。

パッケージ名は完全なパスでなくてもよく、その場合はGOPATH以下からマッチするものを探してきます。

ソースは `src/cmd/doc/` 以下にあります。

// TODO: godoc との関係
// TODO: 概要

=== 引数の解決（`parseArgs`）

最初に、引数で指定された要件にしたがってドキュメントの元となるソースコードを取得します。

`go doc` への引数の与え方はさまざまで、パッケージを指定する方法には次の3パターンがあります：

a. カレントディレクトリのソースコードを対象にする（例：`go doc`）。
b. 完全なパスで指定されたパッケージを対象にする（例：`go doc encoding/json`）。
c. 指定されたパスの一部からパッケージを探しだす（例：`go doc json`）。

これに加えて、パッケージ内のシンボルおよびそのメソッドも指定されることがあります。

カレントディレクトリを対象にする場合およびパッケージが指定されている場合（aおよびb）は、`go/build` のAPI `build.Import` を使って簡単にソースコードの所在を示す `build.Package` が得られます。

そうでない場合（c）、パスの一部が一致するパッケージを発見する必要があります。ここでも `go/build` のAPIを利用し、`build.Default.GOROOT` と `build.Default.GOPATH` 以下のディレクトリを探索します。`go doc` コマンドが実行された時点でこの探索のためのgoroutineが起動していて、すばやく結果を返せるようになっています。

=== ソースコードの解析（`parsePackage`）

ドキュメント情報を得るためには、ソースコードを解析する必要があります。パッケージの情報が手元にあるので `parser.ParseDir` でディレクトリ内のファイルを一度に解析できますが、その際第3引数の `filter` を指定して `GoFiles` や `CgoFiles` に含まれないものを除去します。こうすることで、実行環境（`GOOS` や `GOARCH`）に合わせたソースコードのみを解析対象としています。

[source,go]
----
pkgs, err := parser.ParseDir(fs, pkg.Dir, include, parser.ParseComments)
----

その後 `doc.New` して得られた `doc.Package` から `Package` 構造体を生成します。

=== ドキュメントの表示（`Pacakge.packageDoc` など）

`Package` 構造体の以下のメソッドがモードに応じて選ばれ、ユーザに表示される内容を生成します。

* `packageDoc` ... パッケージのドキュメントを表示
* `symbolDoc`  ... シンボル（型、関数、メソッドなど）のドキュメントを表示
* `methodDoc`  ... ある型のメソッドのドキュメントを表示

ドキュメントを表示するなかで対象のソースコードにおける定義が必要になった場合（`go doc go/ast File` など）、`format.Node` で生成されます。`ast.FuncDecl` を表示する際は `Body` フィールドに `nil` を代入することで、宣言のみが表示されるようにしています。

== gofmt

Goにおいて特徴的なコマンドで、ソースコードを標準的なスタイルにフォーマットします。ほとんどのGoプログラマが利用しているコマンドです（たぶん）。

=== gofmtの主なインタフェース

何もオプションを指定しない場合、gofmtは引数のファイルまたは標準入力をフォーマットして、標準出力に印字します。

よく利用されるのは `-w` で、これが指定された場合結果は引数のファイルを上書きするのに使われます。また `-d` では、入力の内容と結果の `diff` が表示されます。

ソースコードは `src/cmd/gofmt` 以下にあります。

=== ソースコードの印字

WARNING: WIP

=== `gofmt -s`: ソースをシンプルにする

通常gofmtが行うのはソースコードの整形のみで、抽象構文木の構造が変わるような変更を行いませんが、`-s` や  `-r` を指定することでより積極的なフォーマットが可能です。

このオプションが指定された場合、ソースコードの印字の前に `simplify(f *ast.File)` が呼び出され、構文木の書き換えが行われます。以下でその流れを見ていきましょう。

最初に `const ()` のような空の宣言が取り除かれます。これは `ast.File.Decls` を書き換えることで実現できます（gosource:src/cmd/gofmt/simplify.go#L137-146[go1.6,removeEmptyDeclGroups]）。

それから、構文木を辿って単純化が行われます。適用されるのは以下のルールになります。

// TODO 例
* 複合リテラルの単純化
* スライスの単純化（`s[a:len(s)]` → `s[a:]`）
* for/range文の単純化（`for _ = range` → `for range`）

スライスとfor/range文の単純化は比較的単純な作業で、type assertionを利用しながら構文木を探索し、求める構造に合致するノードを発見します。合致した場合、消し去りたい部分を表すフィールドに `nil` を代入することで結果のソースコードから削除しています。

// simplify -> simplifier.Visit -> match

複合リテラルの単純化の内部で使用されているのが `func match(m map[string]reflect.Value, pattern, val reflect.Value) bool` 関数です（gosource:src/cmd/gofmt/rewrite.go#L160[go1.6]）。`match()` は構文ノード（`ast.Node`）への `reflect.Value` を2つ引数に取り、それらが一致するかをチェックします。

`match()` には2種類のモードがあり、

* 引数 `m` が `nil` の場合は、2つの `reflect.Value` の表す `ast.Node` が同じ値であるかを再帰的にチェックします。
** この際、<<ソースコード中の位置>>などの値が異なっていても基本的に無視します。
* 引数 `m` が非 `nil` の場合には、`pattern` 引数の表すパターンに `val` が一致するかを見ます（後述）。

ここでは前者の場合のみが起こり、複合リテラルの外側と内側の型（を表す構文ノード）が等しい場合には内側の型を消去する、という処理を行っています。

=== `gofmt -r`: ソースを書き換える

さらに高度な機能として、引数に指定されたパターンに従ってソースコードを書き換えることもできます。以下のように `\->` を2つのGoの式で挟んだ形式によってコードの書き換え規則を指定します。

....
gofmt -r 'a[b:len(a)] -> a[b:]' ...
....

書き換え規則の入力は、まず2つの `ast.Expr` として解釈されます（gosource:src/cmd/gofmt/rewrite.go#L19-32[go1.6,initRewrite]）。

実際の処理は `rewriteFile`（gosource:src/cmd/gofmt/rewrite.go#L57-82[go1.6,rewriteFile]）です。内部では、構文木を表すデータ構造を `reflect` APIによって探索しながら `rewriteVal` で書き換えを行います（gosource:src/cmd/gofmt/rewrite.go#L64-77[go1.6,rewriteVal]）。探索中に出現した構文ノードがパターンに一致した場合、マッチ結果とユーザの入力にしたがってノードを置き換えます。

前述のように、書き換えは書き換え元のパターン（例えば `a[b:len(a)]`）と書き換え先（`a[b:]`）の組によって指定されます。パターンはGoの式になっていて、中でも小文字1文字からなる識別子は「ワイルドカード」として扱われ、任意の式にマッチします。例えば `a + b` というパターンは、以下のような式にマッチします。

[source,go]
----
f.g(x) + "y"       // a=f.g(x), b="y"
(1 / 2) + (3 + 4)  // a=(1 / 2), b=(3 + 4) および a=3, b=4
----

2番目の例のように、パターンの探索は再帰的に行われます。パターンとの一致のチェックには、前述の `match` 関数を用います。ワイルドカードに一致した構文ノードは引数 `m` に格納され、その後のチェックと書き換え後のノードの生成に利用されます。

// TODO: もっと詳しくわかりやすく

/////

* 抽象構文木を表現するデータ構造を `reflect` によって再帰的に探索する `apply`、
* そこで発見した値が `pattern` にマッチした場合、マッチ結果を利用してデータ構造を書き換えます

* `func subst(m map[string]reflect.Value, pattern reflect.Value, pos reflect.Value) reflect.Value`（gosource:src/cmd/gofmt/rewrite.go#L244-303[go1.6,subst]）
** `pattern` には `repl` が渡る。`pat` を `val` にマッチさせた結果の `m` と `repl` でもって新しい値を作る
** `pattern` が `token.Pos` の `reflect.Value` であることもあるっぽい
** `pos` がポイントっぽい
** L263 の `pattern.Type() == positionType` は使われてなさそう
*** そんなことないか。`pattern` には ast.Node の各フィールドの reflect.Value が入る？ match() しないから無理筋?
*** かと思ったけど `apply` の中で ast.StarExpr.Star とかを下るか
* `func apply(f func(reflect.Value) reflect.Value, val reflect.Value) reflect.Value`（gosource:src/cmd/gofmt/rewrite.go#L115-150[go1.6,subst]）
** フィールドを `f` で書き換える
** `apply` でフィールドを辿って下っていく

/////

== stringer

== guru

== goimports

== gddo
