#!/usr/bin/env ruby

require 'asciidoctor'
require 'cgi'
require 'tempfile'
require 'json'

require './macro.rb'

CODE_PLACEHOLDER = '◆◆'

doc = Asciidoctor.load_file('index.adoc', safe: Asciidoctor::SafeMode::UNSAFE, sourcemap: true)
doc.delete_attribute 'toc'

lines = []

doc.query do |node|
  node.context == :section || node.context == :paragraph || node.context == :ulist || node.context == :olist || node.context == :dlist
end.map do |node|
  s = if node.context == :section
    node.title
  elsif node.context == :ulist
    node.items.map do |i|
      i.text
    end.join("\n")
  else
    node.render
  end
    .gsub(%r( ?<code\b.*?>.*?</code> ?), CODE_PLACEHOLDER)
    .gsub(%r(（<dfn[^>]*>[a-z ]+?</dfn>）)i, '') # TermMacro。日本語じゃないので除く
    .gsub(/ ?<[^>]*> ?/, '')
    .gsub(/\n+/, "\n")
    .strip

  lines += CGI::unescape_html(s).lines.map do |line|
    {
      line: line.chomp,
      loc:  {
        path:   node.source_location.path,
        lineno: node.source_location.lineno
      }
    }
  end
end

f = Tempfile.open([ 'textlint', '.txt' ]) do |f|
  lines.each do |l|
    f.puts l[:line]
  end
  f
end

success = true

result = JSON.parse(%x(node_modules/.bin/textlint --format json #{f.path}))
result.flat_map do |r|
  r['messages']
end.sort_by do |m|
  m['line']
end.each do |m|
  loc = lines[m['line']-1][:loc]
  if m['message'].index(%(don't repeat "#{CODE_PLACEHOLDER}))
    # nop
  else
    success = false
    puts "#{loc[:path]}:#{loc[:lineno]}:#{m['message']} (#{m['ruleId']})"
  end
end

exit success
